name: background_timer_package
description: A Flutter timer that persists and calculates elapsed time when the app is in the background or terminated.
version: 1.0.0
homepage: https://github.com/SamiraElhami/flutter_background_timer
repository: https://github.com/SamiraElhami/flutter_background_timer
issue_tracker: https://github.com/SamiraElhami/flutter_background_timer/issues
environment:
  sdk: ^3.11.0-276.0.dev
  flutter: ">=1.17.0"

dependencies:
  bloc: ^9.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4




