name: background_timer_package
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: ^3.11.0-276.0.dev
  flutter: ">=1.17.0"

dependencies:
  bloc: ^9.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  shared_preferences: ^2.5.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  bloc_test: ^10.0.0
  mocktail: ^1.0.4




